name: apiverve_disposablephone
description: Disposable Phone Number Checker is an API that checks whether a given phone number is a known disposable or temporary number. Useful for fraud prevention, user verification, and security.
version: 1.1.14
homepage: https://apiverve.com/marketplace/disposablephone?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/disposablephone-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
